# Created with komac v2.12.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: NitroSoftware.NitroPro.NLS
PackageVersion: 14.39.0.18
PackageLocale: en-US
Publisher: Nitro
PublisherUrl: https://www.gonitro.com/
PublisherSupportUrl: https://www.gonitro.com/support
PrivacyUrl: https://www.gonitro.com/legal/privacy-policy
Author: Nitro Software, Inc.
PackageName: Nitro PDF Pro (NLS Version)
PackageUrl: https://www.gonitro.com/pdf-pro
License: Proprietary
LicenseUrl: https://www.gonitro.com/legal/terms-of-service
Copyright: © 2005-2024 Nitro Software, Inc. and its licensors. All rights reserved.
CopyrightUrl: https://www.gonitro.com/legal/terms-of-service
ShortDescription: Create, edit, sign, and secure PDF files and digital documents. This is the Nitro Licensing System (NLS) version.
Tags:
- annotate
- annotation
- comment
- conversion
- convert
- ebook
- edit
- editor
- ocr
- pdf
- read
- reader
- viewer
PurchaseUrl: https://www.gonitro.com/pricing
ManifestType: defaultLocale
ManifestVersion: 1.10.0
